version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: go-server-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  server:
    build: .
    container_name: go-server
    ports:
      - "8080:9010"
    depends_on:
      - db

volumes:
  db-data:
